const CONSTANT_TYPES = {
    SET_USER_VALUE: 'SET_USER_VALUE',
    SET_LOADING_VALUE: 'SET_LOADING_VALUE',
    SET_CHNNEL_VALUE: 'SET_CHNNEL_VALUE',
    SET_CHANNELS_VALUE: 'SET_CHANNELS_VALUE',
    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
    SET_CHANNEL_TOFIND: 'SET_CHANNEL_TOFIND',
    SET_MESSAGE_VALUE: 'SET_MESSAGE_VALUE'
}

export default CONSTANT_TYPES;